- name: Configuring App User in RabbitMQ
  shell: |
    rabbitmqctl add_user roboshop roboshop123; rabbitmqctl set_user_tags roboshop administrator; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"

- name: Start RabbitMQ
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

